name: Standard CI
on: push
jobs:
    build-test:
        name: Build Test and Deploy
        runs-on: ubuntu@latest
        steps:
            - name: checkout latest code
              uses: actions/checkout@v4

            - name: Set up node
              uses: actions/setup-node@v4
              with:
                  node-version: '18'

            - name: Run lint
              run: npm run lint

            - name: Build project
              run: npm run build    

            - name: Run tests
              run: npm run test

            - name: Run Deploy
              run: npm run deploy

            