name: Standard CI
on: push
jobs:
    build-test:
        name: Build Test and Deploy
        runs-on: ubuntu@latest
        steps:
            -name: checkout latest code
             uses: actions/checkout@v4